site_name: Calliope-seminar
repo_uri: https://github.com/tetsu26/Calliope-seminar
copyright: Nakata Laboratory, Tohoku University 
theme:
  name: material
  language: 'ja'
  feature:
    tabs: true

nav:
  - README.md
  - chapter_1.md
  - chapter_2.md

extra:
  search:
    language: 'ja'
  

extra_javascript: 
    - "js/extra.js"
    - "https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.1/MathJax.js?config=TeX-AMS_HTML"
  # - http://cdn.mathjax.org/mathjax/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML
  
extra_css:
  - "//fonts.googleapis.com/earlyaccess/notosansjp.css"
  - "//fonts.googleapis.com/css?family=Open+Sans:600,800"
  - "extra.css"
  - "https://maxcdn.bootstrapcdn.com/font-awesome/4.6.1/css/font-awesome.min.css"

markdown_extensions:
  - admonition
  - footnotes
  - def_list
  - pymdownx.smartsymbols
  - pymdownx.keys
  - codehilite:
      linenums: true
  - pymdownx.emoji:
      emoji_generator: !!python/name:pymdownx.emoji.to_svg
