site_name: Calliope-seminar
site_url: https://tetsu26.github.io/Calliope-seminar
site_author: Tetsushi Amano, Tenchi Suematsu
copyright: Nakata Laboratory, Tohoku University 

repo_name: tetsu26/Calliope-seminar
repo_url: https://github.com/tetsu26/Calliope-seminar
edit_uri: ""

theme:
  name: material
  language: 'ja'
  feature:
    tabs: true
  icon:
    logo: material/school
    repo: fontawesome/brands/git-alt
  

nav:
  - README.md
  - chapter_1.md
  - chapter_2.md

extra:
  search:
    language: 'ja'
  

extra_javascript: 
  - "https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.1/MathJax.js?config=TeX-AMS_HTML"
  # - http://cdn.mathjax.org/mathjax/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML
  
extra_css:
  - "//fonts.googleapis.com/earlyaccess/notosansjp.css"
  - "//fonts.googleapis.com/css?family=Open+Sans:600,800"
  - "css/custom.css"
  - "https://maxcdn.bootstrapcdn.com/font-awesome/4.6.1/css/font-awesome.min.css"

markdown_extensions:
  - admonition
  - footnotes
  - def_list
  - pymdownx.smartsymbols
  - pymdownx.keys
  - pymdownx.details
  - fontawesome_markdown
  - codehilite:
      linenums: true
  - pymdownx.emoji:
      emoji_generator: !!python/name:pymdownx.emoji.to_svg

google_analytics:
  - 'UA-177930089-1'
  - 'auto'